name: big_earth_net
environment:
    image:
        gpu: docker.io/junhongshen/nb360:updatenew
hyperparameters:
    dataset: BigEarth
    embedder_dataset: CIFAR10 # hg38, text, text_roberta_large, text_llama, text_llama2, text_pythia_1b, text_flan_t5_small, text_flan_t5_base, text_flan_t5_large
    objective: MMD # otdd-exact, MMD
    weight: base # roberta, hyenadna-small-32k-seqlen, roberta-large, c, pythia-1b, llama, llama2, flan-t5-small, flan-t5-base, flan-t5-large
    nlayers: full # one, full
    maxsamples: 30 # 64, 256
    target_seq_len: 256 # 512 for roberta, 2048 for llama, 4096 for llama2, 2048 for pythia-1b, 1024 for flan t5

    experiment_id: 12

    seed: 0
    epochs: 60 # 13
    pretrain_epochs: 0 # 0, 20
    embedder_epochs: 1 # 60, 20
    predictor_epochs: 0

    joint_optim: True
    alpha: 0 # weight for otdd 
    beta: 1 # weight for bce
    finetune_method: all # all, lora, freeze

    drop_out: 0 #0
    activation: None

    use_wandb: False
    wandb_key: "ef4b923327eb2a110fda334efee4ec80feee4bc7" # add your own wandb key

    embedder_type: "resnet" # dash-->resnet, unet, dash random, unet-dash
    embedder_init: "random" # random, pretrained
    ks: [9, 7, 5, 11, 5, 7, 9, 11, 11]  
    ds: [1, 5, 3, 1, 3, 7, 1, 7, 7]
    


    
    batch_size: 1
    eval_batch_size: 1000
    accum: 1
    clip: -1 
    validation_freq: 1

    optimizer:
        name: AdamW
        params:
            lr: 0.0003 # 0.00001 for pythia-1b, 0.001   
            betas: [0.9, 0.98] 
            weight_decay: 0.001
            momentum: 0.9
    
    scheduler:  
        name: WarmupLR
        params:
            warmup_epochs: 5
            decay_epochs: 65
            sched: [20, 40, 60]
            base: 0.2

    no_warmup_scheduler:  
        name: StepLR
        params:
            warmup_epochs: 10
            decay_epochs: 80
            sched: [20, 40, 60]
            base: 0.2

    num_workers: 4
    reproducibility: False
    valid_split: False

min_validation_period:
    epochs: 1
bind_mounts:
    - host_path: /tmp
      container_path: /data
    - host_path: /tmp
      container_path: /root/.cache
resources:
  slots_per_trial: 1
records_per_epoch: 9281
searcher:
  name:  single
  metric: accuracy
  smaller_is_better: false
  max_length:
    epochs: 1
max_restarts: 0
entrypoint: python3 -W ignore main.py